name: Docker
on: push

jobs:
  test-docker:
    runs-on: ubuntu-latest
    container:
      image: node:12
      env:
        NODE_ENV: develpment
      ports:
        - 80
    steps:
      - name: Display node
        run: node -v