name: First Workflow
on: [push]

jobs:
    run_first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Display some Text
            run: echo "Some Text"

        


            