name: Fiveth Workflow
on:
  issues:
    types: [edited, deleted]
  pull_reqest:
    types: [assigned, closed]
jobs:
    run_first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Event Vars
            run: |
              echo $GITHUB_SHA
              echo $GITHUB_REF

          