name: Fiveth Workflow
on: [push, issues]

jobs:
    run_first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Event Vars
            run: |
              echo $GITHUB_SHA
              echo $GITHUB_REF

          