name: Fourtenth Workflow
on: workflow_dispatch

jobs:
   first-job:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Cach node modules
         id: cache-step
         uses: actions/cache@v3
         with:
            path: ~/.npm
            key: "cache-file"
       - name: Display Cache
         run: echo '${{ steps.cache-step.outputs }}'
       - name: Install node_modul
         run: npm install  
