name: Nine Workflow
on:
  repository_dispatch:
    types: [test]

  
  
jobs:
    run_first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Event Vars
            run: "echo "Title: ${{ github.event.client_playload.titleTest }}"
              