name: Third Workflow
on: [push]

jobs:
    run_first-command:
      runs-on: ubuntu-latest
      steps:
        - name: Comand in Multiline
          run: ls -a
        - name: Copy Files
          run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:${{secret.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
            git fetch origin
            git checkout main
        - name: List Files
          run: ls -a
     